### ISSUE TITLE
Question about the Performance

### ISSUE THREAD

**Issue by chenhongyu2048** [efeslab/Nanoflow#11]
I have read the nanoflow paper and still have a question: in part6.5 and pic13, maybe the baseline `non-overlap`(sequentially running all operations) has only optimization of kernel implmentation(cutlass and msccl based) and Top-level scheduling?
btw, thanks for your work, which has answered a lot of my questions.

**Comment by serendipity-zk** [comment]
Yes. The non-overlapping baseline uses the same set of optimised kernels while not splitting into any nanobatches or overlapping operations.

**Comment by chenhongyu2048** [comment]
thanks for your kind help~
