### ISSUE TITLE
How much CPU RAM to compile?

### ISSUE THREAD

**Issue by benjamin-marie** [efeslab/Nanoflow#12]
I'm trying to install it but I ran out of CPU RAM when I run:

```
yes | ./setup.sh
```

I tried with a machine with 50 GB of CPU RAM (and another with 24 GB). Is it normal or am I missing something?

**Comment by serendipity-zk** [comment]
If you want to compile it on a 50G RAM machine, I would recommend reducing the number of parallel compile works.

**Comment by AlongWY** [comment]
The pull request #6 make a auto build script, you can download from [here](https://github.com/AlongWY/Nanoflow/actions/runs/10617958844).

**Comment by benjamin-marie** [comment]
Thanks!
It worked after reducing the number of parallel processes for compilation.
