### ISSUE TITLE
How will this framwork control SMs for each kernel?

### ISSUE THREAD

**Issue by chenhongyu2048** [efeslab/Nanoflow#13]
After I read the paper and some of the code, I'm still kind of curious about this question: how will NanoFlow controls the SMs for different kernel?
Such as cutlass based gemm, maybe by setting different cta in the template?

**Comment by chenhongyu2048** [comment]
I find in comm kernel, it will send `nblocks` to control number of SMs. But for gemm kernel, it is not so obvious.

**Comment by yzh119** [comment]
The way nanoflow controls sm usage for each kernel is limiting the grid size of each kernel.
If each CTA uses a large register/shared memory size, then each SM can only execute one CTA at a time, the SM usage for this kernel equals the grid size.

When the number of tiles exceeds grid size, nanoflow executes these tiles waves by waves like persistent kernels (you can refer to [stream-k](https://arxiv.org/pdf/2301.03598)).

**Comment by chenhongyu2048** [comment]
Thanks! As far as I know, the cutlass controls kernel's grid size using the problem size and ShapeMMAThreadblock. Is this right?

And if so, nanoflow will automatically select the optimal ShapeMMAThreadBlock on the premise of not starting more SMs than the limit number?

**Comment by yzh119** [comment]
> the cutlass controls kernel's grid size using the problem size and ShapeMMAThreadblock. Is this right?

Yes, the grid size is determined by `cta_m`/`cta_n`/`cta_k`:
https://github.com/efeslab/Nanoflow/blob/22f0b48739d3a9ad1d8c82f956906b3bc58d519b/pipeline/include/cutlassGemmWrapperImpl.cuh#L92

and their values are generated in https://github.com/efeslab/Nanoflow/blob/22f0b48739d3a9ad1d8c82f956906b3bc58d519b/pipeline/src/generate-gemm/genGEMM.py

For attentions, the grid size is fixed here:
https://github.com/efeslab/Nanoflow/blob/22f0b48739d3a9ad1d8c82f956906b3bc58d519b/gemv/include/attention/prefill.cuh#L1842

**Comment by chenhongyu2048** [comment]
Thank you very much for your help! This completely answered my doubts. 
Your work in both nanoflow and punica has helped me quite a bit.

**Comment by HarryWu99** [comment]
I wonder if changing the grid size just by changing `cta_m/cta_n/cta_k` will have side effects. 
For example, when `grid size=256`, the execution time of a block is $T$, but if increase `cta_m/cta_n` letting the `grid size=64`, will the time of one block be greater than $4T$, because of register overflow or shared memory competition?
@yzh119
