### ISSUE TITLE
How to handle comp-comm overlapping?

### ISSUE THREAD

**Issue by chenhongyu2048** [efeslab/Nanoflow#14]
Maybe this question isn't all that relevant to nanoflow, but I'd still like to take this opportunity to ask for help from those of you who are experienced.

I used a cutlass gemm kernel with a grid size of <<<128,1,1>>> and my GPU has 142 SMs, so apparently there is a surplus of SMs. But after I started two P2P nccl kernels at the same time, it caused both my compute and communication kernels to be longer (up to 2x in comm).

I would like to ask if this is an issue with NCCL? (Because the ncclsend/recv kernel only seems to start the kernel with <<<1,1,1>>> grid size) if so, I would probably switch to mscclpp.

**Comment by chenhongyu2048** [comment]
update: I got a suggestion that the gemm kernel and communication kernel will still compete for memory bandwidth though they will not compete for SMs. 
I wonder if nanoflow has ever had a similar problem.

**Comment by yzh119** [comment]
> gemm kernel and communication kernel will still compete for memory bandwidth though they will not compete for SMs.

That's true and I don't think nanoflow has a good solution for that.

Ideally we can create a mutex-like structure, and only performs network communication when gemm memory transactions finishes, that requires signaling across kernels and I'm not aware of an efficient way to do that.

**Comment by chenhongyu2048** [comment]
Thank you for your generous and candid help. 
I don't think I have any more problems, at least for now. 
Thanks again and sincerely.
