### ISSUE TITLE
setup.sh not working

### ISSUE THREAD

**Issue by didlawowo** [efeslab/Nanoflow#16]
the setup sh need to be launch in root mode

also install package not in venv

and also try to launch script not existing 

`
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
./setup.sh: line 84: ./test_compute: No such file or directory`

**Comment by serendipity-zk** [comment]
We recommend using docker for setting up the environment and thus assume root mode.
