### ISSUE TITLE
No online serving code yet?

### ISSUE THREAD

**Issue by HarryWu99** [efeslab/Nanoflow#20]
I couldn't find the code for online serving. Has this part not been open-sourced yet? 

I would like to reproduce `Figure 11. Comparison of the online latency.`

**Comment by HarryWu99** [comment]
```
datasets/utils/generate_real_trace.sh
pipeline/eval/eval-real-online-1024/run.py
```
Looks like the relevant code is here, but lacks doc on how to use it

**Comment by serendipity-zk** [comment]
Hi, all the tests including online benchmarks can be invoked by perf.sh.
