### ISSUE TITLE
error: peer access is not supported between these two device

### ISSUE THREAD

**Issue by Ox0400** [efeslab/Nanoflow#22]
I tried run llama3-70B, raise the error `peer access is not supported between these two device`

**Comment by serendipity-zk** [comment]
Hi, what devices are you using? Some GPU models does not support peer access.

**Comment by Ox0400** [comment]
> Hi, what devices are you using? Some GPU models does not support peer access.

Hi, was using Nvidia 3090 * 8

**Comment by serendipity-zk** [comment]
3090 does not support peer access. Only workstation cards (e.g. Ada 6000) or V100, A100, H100 have this feature.

**Comment by Ox0400** [comment]
> 3090 does not support peer access. Only workstation cards (e.g. Ada 6000) or V100, A100, H100 have this feature.

Thanks for your reply.
