### ISSUE TITLE
How to reproduce the benchmark?

### ISSUE THREAD

**Issue by alexngng** [efeslab/Nanoflow#4]
A creative work! 
I want to reproduce the benchmark so  that I can use the ShareGPT dataset or other dataset. But I can't find the benchmark reproduce .py file or other scripts.

**Comment by serendipity-zk** [comment]
We will release the code for reproducing the results in the incoming week.

**Comment by oliverhu** [comment]
Any update on the code to reproduce the results?

**Comment by wDevil** [comment]
>Any update on the code to reproduce the results?

+1
